workflow.go, workflow_test.go
Enforcing the alignment of these two. I think I previously didn't do it as they were generic but its simple enough to add to a test file. Will break tests passing if they dont align as opposed to creating a satus type in the workflow package just for this enforcement. Currently nothing uses workflow.API but I believe there is value here to use it in testing when you dont want the actual workflow running.
=> workflow: Align API and Workflow implementation

adapters/adaptertest/connector.go, adapters/adaptertest/eventstreaming.go, adapters/reflexstreamer/reflex.go, await.go, await_test.go, builder.go, builder_test.go, connector.go, consumer.go, delete.go, go.mod, go.sum, metrics_test.go, options.go, outbox.go, runstate_test.go, schedule.go, schedule_test.go, state_test.go, testing.go, testing_test.go, timeout.go, visualiser_test.go, workflow.go, workflow_test.go
This MR:
- Cleans up the repetitive pattern of setting options for processes.
- Adds the ability to set the defaults config for all the processes in the workflow.
- Adds a benchmark test.
-  Removes the timeout store as a core dependency and allows for it to be optional based on whether the user needs to use timeouts or not. This also results in not running 2 goroutines used to manage the process if its not being used.
=> workflow: Clean up options patterns and allow workflow defaults

adapters/adaptertest/recordstore.go, filter.go, filter_test.go
This is to avoid having to refer to a specific status type in the context of dealing with the record store where generic types are not of a concern. At this level status should just be an `int` . Generics should never leak onto the adapter interfaces and should always be wire format.
=> workflow: Use int value for status filter to avoid generic assertion

.github/workflows/mirror-to-codecommit.yml
adding the workflow to mirror repo for DR purposes
=> workflow: add mirror for DR

README.md
The examples were moved to `_examples` so that they are ignored by the go tool. The README sadly was not informed.
=> readme: Update examples link to _examples

_examples/callback/callback.go, _examples/connector/connector.go, _examples/gettingstarted/gettingstarted.go, _examples/schedule/schedule.go, _examples/timeout/timeout.go
=> fix: Fix wrong parameter type in example

adapters/reflexstreamer/reflex.go, adapters/reflexstreamer/reflex_test.go
Currently rsql.Clone does not copy the gap fillers over so this forces a gap filler to be added once
=> reflexstreamer: Register fill gaps on clone

testdata/graph-visualisation.md, visualiser.go, visualiser_test.go
This MR updates the diagram function from `MermaidDiagram` -> `CreateDiagram` which seems to be far more intuitive. Also a small bug where statuses that have spaces break the diagram is fixed in this MR.
=> workflow: Rename diagram creation function and signature

adapters/jlog/go.mod, adapters/kafkastreamer/go.mod, adapters/reflexstreamer/go.mod, adapters/sqlstore/go.mod, adapters/sqltimeout/go.mod
Small clean up of referencing a no longer existing  version (v0.1.2) 🤦‍♂️
=> adapters: Update workflow reference

marshal.go, testing.go, testing_test.go, unmarshal.go
I have started to see some json.Marshaler implementations and the testing util func `Require` needs to be provided with an object that has gone through the encode and decode process. To avoid the user needing to do this the Require func is being updated to take the provided expected data and encode and then decode it the same way the data in the workflow. This is a developer experience (DX) change at the heart of it as it's frustrating to need to adjust default zero values of objects or reformat underlying strings etc.
=> workflow: Support json.Marshaler implementations for Require

workflow.go, workflow_internal_test.go
Adding a human readable 'process' name to error log to link the process in the logs to the metrics and some alerts.
=> workflow: Add process name to error logs

README.md, adapters/adaptertest/recordstore.go, await.go, builder.go, builder_internal_test.go, event.go, hook.go, hook_internal_test.go, hook_test.go, metrics_test.go, record.go, run.go, runstate.go, runstate_internal_test.go, runstate_test.go, testing.go, topic.go, update.go, update_internal_test.go, workflow.go, workflow_test.go
This MR / PR focuses on adding the ability to write a short hand consumer for RunState changes. This was always possible before but would require the user to use the correct topic setup or if using Reflex using a StreamFunc to stream and filter by RunState. These are simpler and more discoverable being part of the builder and does not extend the feature set but rather enhances the discoverability of what already exists.
=> workflow: Add hooks to builder

.github/workflows/tests.yml
- Removed 1.21 runs
- Update to use 1.23 (run as part of 1.x option)
=> workflows: Update go version

README.md
Updates the README with best practices, explanation of the Run, and the role of the role scheduler.
=> readme: Add best practices, overview, and run explanation

adapters/webui/internal/frontend/home.html, adapters/webui/internal/frontend/main.js
This MR introduces some UI changes to show the TriggeredAt column first in a simple manner. If the tiggered at is on the current day it only shows time  and if its on a different day but same month then shows the day and not the month and so forth.
This MR also introduces a Duration column to show how long the workflow took to complete and if it's still running then the duration increases on every refresh or poll.
Before: 
After:
=> webui: Add simplified trigger date and add processing duration

_examples/schedule/schedule_test.go, adapters/webui/internal/frontend/home.html, await.go, builder.go, callback.go, callback_internal_test.go, connector.go, consumer.go, consumer_internal_test.go, delete.go, hook.go, outbox.go, runstate_test.go, schedule.go, state.go, testing.go, timeout.go, timeout_internal_test.go, trigger.go, visualiser.go, workflow.go, workflow_test.go
This renames the `Name` field part of the Workflow struct and makes it a method on the workflow.API interface.
=> api: Add Name method to API interface

_examples/connector/connector.go, adapters/adaptertest/connector.go, builder_internal_test.go, connector.go, state_test.go, workflow_test.go
This allows the connecto functions to have unit tests written where a mock implementation can be provided as the workflow and not the actual implementation of the workflow. This allows for things like asserting certain calls that should be made back to the workflow without the need to use the actual implementation or providing an empty implementation.
=> connector: Use API interface to improve testability of connector funcs

adapters/adaptertest/recordstore.go, adapters/webui/internal/api/list.go, filter.go
This MR changes the `FilterByStatus` function to take in anything that is a underlying int, int32, or int64 so that aliases may be passed in such as the status that is being used. The `StatusType` is not being used as the stringer is not needed.
=> recordstore/filter: Convert int64 param to any underlying int variation 

autopause_internal_test.go, run_test.go, testing.go
This MR changes NewTestingRun to return a pointer to the run. This is to align with the norm that `New` returns a pointer.
=> testing: Return pointer of workflow run for constructor `NewTestingRun`

_examples/callback/callback_test.go, _examples/connector/connector.go, _examples/gettingstarted/gettingstarted_test.go, _examples/schedule/schedule_test.go, _examples/timeout/timeout_test.go, _examples/webui/main.go, adapters/adaptertest/connector.go, adapters/adaptertest/eventstreaming.go, adapters/reflexstreamer/streamfunc_test.go, autopause_test.go, await_test.go, builder.go, builder_internal_test.go, hook_test.go, metrics_test.go, runstate_test.go, schedule.go, schedule_test.go, testing_test.go, trigger.go, trigger_internal_test.go, workflow.go, workflow_test.go
This MR removes the requirement to specify the starting point of the workflow run. Instead there is a trigger option that allows for the workflow run to be started at a specific point. This simplifies the use of the workflow by not needing to be familiar with the steps or order of the steps. This also allows for the small edge case of needing to start at a different point to be supported via options rather than the main interface of triggering a workflow run.
=> trigger: Remove need for specifying starting point

adapters/sqlstore/sqlstore.go
If a replica exists then there is a good chance, at low polling frequency, that old outbox records will be listed. This ensures that the time critical changes are always accurate. The table cannot grow very large due to the deletion after processing so this should be sustainable.
=> sqlstore: Use writer instance for time critical read

adapters/reflexstreamer/connector_test.go, adapters/reflexstreamer/reflex.go
Since reflex has been updated to accept a `*sql.DB` to `*sql.Tx` the transaction is not needed and can be removed.
=> reflexstreamer: Remove transaction from event insertion

.github/workflows/tests.yml, builder_internal_test.go, metrics_test.go, outbox.go, runstate_test.go, workflow_test.go
The outbox options had a different pattern than the default options for the processes and this aligns with that pattern plus additional unit tests.
=> outbox: Align with default options pattern and test

adapters/sqlstore/schema.sql, adapters/sqlstore/util.go, adapters/sqlstore/util_test.go
Allows for null meta which is needed for anyone migrating to the newest version that writes meta.
=> adapters/sqlstore: Handle null meta for migrating users
